package com.application.bmiobesity

enum class PoseTrackingIndex(val index: Int)  {
    NOSE(0),
    LEFT_EYES_INNER(1),
    LEFT_EYES(2),
    LEFT_EYES_OUTER(3),
    RIGHT_EYES_INNER(4),
    RIGHT_EYES(5),
    RIGHT_EYES_OUTER(6),
    LEFT_EAR(7),
    RIGHT_EAR(8),
    LEFT_MOUNT(9),
    RIGHT_MOUNT(10),
    LEFT_SHOULDER(11),
    RIGHT_SHOULDER(12),
    LEFT_ELBOW(13),
    RIGHT_ELBOW(14),
    LEFT_WRIST(15),
    RIGHT_WRIST(16),
    LEFT_PINKY(17),
    RIGHT_PINKY(18),
    LEFT_INDEX(19),
    RIGHT_INDEX(20),
    LEFT_THUMB(21),
    RIGHT_THUMB(22),
    LEFT_HIP(23),
    RIGHT_HIP(24),
    LEFT_KNEE(25),
    RIGHT_KNEE(26),
    LEFT_ANKLE(27),
    RIGHT_ANKLE(28),
    LEFT_HEEL(29),
    RIGHT_HEEL(30),
    LEFT_FOOT(31),
    RIGHT_FOOT(32)
}